### PR TITLE
Merge interim SVT 2.1 code

### PR DESCRIPTION
**Pull request by gabrielmcg**
Add playbooks for:

client bundle,
kubectl
helm

sysdig/rbac
nfs-provisioner/rbac

prometheus operator
ucp metrics

k8s guestbook on redis
mysql/wordrpress with NFS
alpine, nginx helm charts

### CODE REVIEW

**Review by moyni77 — APPROVED** [review]
Looks good to go into Synergy devel branch.

**Review by ghost — COMMENTED** [review]
all the files looking for vars and vault in group_vars will fail as they are now in group_vars/all

**Comment by gabrielmcg** [comment]
> all the files looking for vars and vault in group_vars will fail as they are now in group_vars/all

Yes - should be fixed now 

(we haven't made this change in the SVT repo yet - not sure if I want to do it right before release)

**Comment by ghost** [comment]
> > all the files looking for vars and vault in group_vars will fail as they are now in group_vars/all
> 
> Yes - should be fixed now
> 
> (we haven't made this change in the SVT repo yet - not sure if I want to do it right before release)

I think you don;t want to update the SVT repo at this point of the release cycle (you would have to update the doc and you probably don;t want to do it now as the changes are significant) Regarding this repo make sure the code in this PR is working before merging.  I will let you do the merge yourself as this is your code so you get the credit.

**Comment by gabrielmcg** [comment]
> > > all the files looking for vars and vault in group_vars will fail as they are now in group_vars/all
> > 
> > 
> > Yes - should be fixed now
> > (we haven't made this change in the SVT repo yet - not sure if I want to do it right before release)
> 
> I think you don;t want to update the SVT repo at this point of the release cycle (you would have to update the doc and you probably don;t want to do it now as the changes are significant) Regarding this repo make sure the code in this PR is working before merging. I will let you do the merge yourself as this is your code so you get the credit.


I tested all these playbooks today with group_vars/all on SVT - I don't have a Synergy setup yet , so maybe I wasn't the best person to do the merge...

I propose to proceed with the merge - Nick is then going to do a Synergy build, so we can test these playbooks explicitly. In theory, it should be fine as they all run outside site.yml so should have no direct impact - we can fix any issues as we see them...

**Pull request merged**
