### PR TITLE
inventory reorg and RedHat BM provisioning (singleframe)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by moyni77 — COMMENTED** [review]
The file bms.yml has a hard coded password, shouldn't this be pulled from the vaults file? 
Also noticed a number of files with clh- should these be altered to have hpe- ? Polices clh-bronze, clh-gold, and many cld-hostnames.

**Comment by ghost** [comment]
@moyni77 Good point regarding the password. for the files in group_vars/vars, I will leave the clh-* values for now, we can do the cleanup when we merge in master

**Comment by ghost** [comment]
I have moved the group_vars/vars and group_vars/vault files to group_vars/all and modified the playbooks (almost all of them) accordingly. I also have modified the backup playbooks so that they save the hosts file plus the content of group_vars (including subfolders)

**Review by daveolker — COMMENTED** [review]
The file group_vars/bms.yml has hard coded values including passwords.  This should be changed to use vault for password and configurable variables for the hostname, username, api_version, etc.

I personally don't like the terms "linux_box" and "windows_box".  I prefer either "linux_node" or "linux_server" to  the term "box".  However, if everyone else prefers "box" it's fine with me.

In the group_vars/windows_box.yml file, what is "toto: 'windows_box'?  What does "toto" mean in this context?

**Comment by ghost** [comment]
@daveolker by definition, a group file is a file containing variables that the users of a playbook can (and must) change.  at some point in time someone must say we use  API 600 (ore 800).  With ansible it can be done in many places, the best place is in the group file which uses oneview.  
regarding the group_vars/windows_box, this is your work. I am only providing the framework at this point in time + something that work for linux boxes.

and I don't see a password in group_vars/bms.yml

**Comment by daveolker** [comment]
@chris7444 I understand the use of the variables file but I never include my customized variable file on a public GitHub repository, especially with passwords.  We provide a vars.sample file so customers know what they need to set, and we should always recommend customers put any passwords in an encrypted vault file.  I certainly embed passwords in my test ring but I never push those files to the public site.

As for bms.yml, I did not say it had a password in it.  My question was what does the line "toto: windows_box" mean?  I haven't seen the "toto" line before.

**Comment by ghost** [comment]
@daveolker 
"I understand the use of the variables file but I never include my customized variable file on a public GitHub repository, especially with passwords"
1) there is no passwords in the files.
2)  my customized files are as valid as any other sample file we could provide. replacing clh-* by hpe-* at this point does not make any difference and as I explained to gabriel who suggested to extend the use of group files, (which is the reason why I made these mods to my original pull request) I am not ready to maintain as many *.sample files as we have group files. the added value = zero. 

" My question was what does the line "toto: windows_box" mean? I haven't seen the "toto" line before."
My answer is the same, you may define variables that only apply to windows boxes using windows_box.yml. As you are looking for the windows side of thing, you may use this file to relocate the windows related variables for example. toto: means nothing here it is just a placeholder.

**Comment by daveolker** [comment]
@chris7444 When I see the group_vars/bms.yml file contains:

oneview_config:
  hostname: synergy1.am2.cloudra.local
  username: Administrator
  **password: plain text password**
  api_version: 600

I've removed the password from this post, but this is what I was referring to.

**Comment by daveolker** [comment]
@chris7444 Ok, I now see that this is the same password issue @moyni77 already pointed out.   Sorry, this is my fault for starting at the top pull request and making comments without checking if later modifications to the pull request addressed my comments.

**Comment by ghost** [comment]
@daveolker 
yes no password in the file. as you can see I had to change the way I initially stored the oneview related parameters because of this. 

oneview_config_hostname: synergy1.am2.cloudra.local
oneview_config_username: Administrator
#oneview_config_password: "Password of the oneview account should be specified in group_vars/vault"
oneview_config_api_version: 600
oneview_config_image_streamer_ip: 10.10.172.122

Please approve. I will no make the change to linux_box/windows_box as you are the only one who was not happy with these names :-) (unless you insist really, really hard). I believe we want to leverage the new code asap. ps: I asked Nick not to approve because I wanted to wait for your feedback.

**Review by daveolker — APPROVED** [review]
Changes look good to me

**Pull request merged**
